---
title: "Risk Tables In Word"
author: "Sarah Gaichas"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

## Stock Assessment Risk Table Examples

```{r}

Tab2 <- readr::read_csv(here::here("data/BBRKC2025risks.csv"))

flextable::flextable(Tab2)|>
  flextable::set_caption("Draft Risk Table for Bristol Bay Red King Crab 2025.") |>
  flextable::width(width = c(3,3,3,3)) |>
  flextable::height(height = 0.8, part = "header") |>
  flextable::height(i = 1, height = 0.8, part = "body") |>
  flextable::height(i = 2, height = 3.5, part = "body") |>
  flextable::hrule(rule = "exact")
```


Source: [2025 Bristol Bay Red King Crab SAFE, Appendix D](https://meetings.npfmc.org/CommentReview/DownloadFile?p=5be176e2-730a-4174-b9ca-2fa22dc53937.pdf&fileName=BBRKC%20SAFE%202025%20Appendix%20D.pdf)



```{r}

Tab3 <- readr::read_csv(here::here("data/SablefishRiskPilot.csv"))

flextable::flextable(Tab3)|>
  flextable::set_caption("Draft Risk Table for West Coast Sablefish 2025.") |>
  flextable::width(width = c(4,4,4))|>
  flextable::height(height = 0.4, part = "header") |>
  flextable::height(i = 1, height = 6.8, part = "body") |>
  flextable::height(i = 2, height = 0.3, part = "body") |>
  flextable::hrule(rule = "exact") |>
  flextable::fontsize(size = 9, part = "all")
```


Source: [Status of the Sablefish 2025](https://www.pcouncil.org/documents/2025/08/g-3-attachment-5-status-of-the-sablefish-off-u-s-west-coast-in-2025.pdf/)
